### ISSUE TITLE
UI Adjustments

### ISSUE THREAD

**Issue by drmwve** [drmwve/Capstone-Project#12]
I think the following changes would make the UI look cleaner:

1. On the Brew Config Screen, the UI elements for quick brews should be above the "Start Brewing" and "Main Menu" buttons. The dropdown menu for the recipes would also look better if it was much wider and taller, and I think there should be a label over all the quick brew stuff that says "Quick Brew" or "Load Quick Brew". 
2. The cleaning button needs to say something else now that it does multiple things. The buttons on that screen are also all over the place.
3. The two buttons at the bottom of the device status screens would be easier to click if they were horizontally spaced instead of vertically.

We should spend some time looking at it and trying to think of more ways to make it look nicer, if we can.

**Comment by TCTaco** [comment]
See https://github.com/drmwve/Capstone-Project/commit/e9505ce005b3a2e4ba287dc8f19582c084e34eb4 and let me know how you feel about it.

**Comment by drmwve** [comment]
@TCTaco this looks great. The only thing that sticks out to me a little bit is the drop down menu. It's currently as wide as the buttons, but there's a whole lot of empty space. I feel like it may look better if it was centered on the buttons and less wide so there wasn't a ton of empty space. Branch off the signals branch for this though, because I think we're pretty close to merging everything else into development.

**Comment by TCTaco** [comment]
I've adjusted the drop down box with ae0af1674cdcd542307d575fe9e12f78bb42930d

I had a couple of bug fixes that needed pushed into this branch so I brought this along with it. I will create a new branch for further refining the UI with any changes starting tomorrow. (I should be done for the night).

**Comment by TCTaco** [comment]
We should pretty much be done with this, I don't see any major changes to the UI and small changes can be made as needed/discovered. I would like you to review the device status screens and provide feedback there, one change I would like to make to it is having the user type in a target temperature rather than using physical buttons. But this kind of depends on what we do with the keyboard issue.

**Comment by drmwve** [comment]
@TCTaco Just took a look, one thing that stands out to me is the temperature controls need an enable/disable button (which calls the setKettlePIDEnabled function). Everything else looks okay, we'll just have to test it.

**Comment by TCTaco** [comment]
https://github.com/drmwve/Capstone-Project/commit/63f46f2142c1672096c40cd97477afb12def6f1d and https://github.com/drmwve/Capstone-Project/commit/6c210fe87299514d7b2a6fb74823fe0585e5a977 address this. Going to close this issue since it's original scope is completed. Raise a new, or reopen this issue if you notice anything else.
